# payment-service/docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - '5434:5432'  # Changed from 5432 to 5434

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
    ports:
      - '9094:9092'  # Changed from 9092 to 9094
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - '2183:2181'  # Changed from 2181 to 2183

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6381:6379'  # Changed from 6379 to 6381